<a href="https://colab.research.google.com/github/AkashSalmuthe/Python-Noteboks/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Creating 1 D Array

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
# Gives Dimension Of array
arr_1d.ndim

1

## Creating 2 D Array

In [5]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr_2d.ndim

2

In [7]:
# How to check size of array



#### Size = Total elments in the array

In [8]:
arr_1d.size

4

In [9]:
arr_2d.size

8

## How to Check Shape of an Array

shape = rows and Columns

In [10]:
arr_1d.shape 

(4,)

In [11]:
arr_2d.shape

(2, 4)

### Get the data type of array

In [12]:
arr_1d.dtype

dtype('int64')

In [13]:
arr_2d.dtype

dtype('int64')

In [14]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Other Operation

In [16]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### One's Array

In [17]:
# Here 5 is number of columns
np.ones(5)

array([1., 1., 1., 1., 1.])

**But we get output in float form ..**

In [18]:
mx_1s = np.ones(5)

In [19]:
mx_1s.dtype

dtype('float64')

**Change this float dtype to integer**

In [20]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## **Zeros**

In [22]:
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
mx_0s = np.zeros((4,6),dtype = int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [24]:
mx_0s = np.zeros((4,6),dtype = bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [25]:
mx_0s = np.zeros((4,6),dtype = str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [28]:
em_str = ''
print(bool(em_str))

False


## **Empty Matrix**

But can't be empty..any random values it can shows

In [29]:
em_mx = np.empty((3,3))
print(em_mx)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


## **Numpy Functions**

## 1. arange()

In [32]:
#  np.arange(start,end,steps)

ar_1d = np.arange(1,13,1)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
# Even No in Between Range 1 to 13

ar_1d = np.arange(1,13,2)
ar_1d

array([ 1,  3,  5,  7,  9, 11])

## 2. linspace()

In [36]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

## 3. Reshape()

Convert 1d array to the onther 2d or 3d array

it also depends on how much elements do you have..

In [38]:
ar_1d = np.arange(1,13,1)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
# Converting to 2d

ar_1d.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
# Converting to the 3D

ar_1d.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [43]:
ar = np.arange(1,19).reshape(3,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


## 4. ravel()

Multidimension array to the 1d array