<a href="https://colab.research.google.com/github/AkashSalmuthe/Python-Noteboks/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Creating 1 D Array

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
# Gives Dimension Of array
arr_1d.ndim

1

## Creating 2 D Array

In [5]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr_2d.ndim

2

In [7]:
# How to check size of array



#### Size = Total elments in the array

In [8]:
arr_1d.size

4

In [9]:
arr_2d.size

8

## How to Check Shape of an Array

shape = rows and Columns

In [10]:
arr_1d.shape 

(4,)

In [11]:
arr_2d.shape

(2, 4)

### Get the data type of array

In [12]:
arr_1d.dtype

dtype('int64')

In [13]:
arr_2d.dtype

dtype('int64')

In [14]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Other Operation

In [16]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### One's Array

In [17]:
# Here 5 is number of columns
np.ones(5)

array([1., 1., 1., 1., 1.])

**But we get output in float form ..**

In [18]:
mx_1s = np.ones(5)

In [19]:
mx_1s.dtype

dtype('float64')

**Change this float dtype to integer**

In [20]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## **Zeros**

In [22]:
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
mx_0s = np.zeros((4,6),dtype = int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [24]:
mx_0s = np.zeros((4,6),dtype = bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [25]:
mx_0s = np.zeros((4,6),dtype = str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [28]:
em_str = ''
print(bool(em_str))

False


## **Empty Matrix**

But can't be empty..any random values it can shows

In [29]:
em_mx = np.empty((3,3))
print(em_mx)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


## **Numpy Functions**

## 1. arange()

In [32]:
#  np.arange(start,end,steps)

ar_1d = np.arange(1,13,1)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
# Even No in Between Range 1 to 13

ar_1d = np.arange(1,13,2)
ar_1d

array([ 1,  3,  5,  7,  9, 11])

## 2. linspace()

In [36]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

## 3. Reshape()

Convert 1d array to the onther 2d or 3d array

it also depends on how much elements do you have..

In [38]:
ar_1d = np.arange(1,13,1)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
# Converting to 2d

ar_1d.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
# Converting to the 3D

ar_1d.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [43]:
ar = np.arange(1,19).reshape(3,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


## 4. ravel()

Multidimension array to the 1d array

In [44]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

## 5. flatten()

works same as ravel

In [47]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])


## 6. Transpose()

In [51]:
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [50]:
ar_trans = ar.transpose()
print(ar_trans)

[[ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]


In [52]:
ar.T

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

# **Mathematic OPeration using Numpy**

In [57]:
# Creating 1d array using arange function and converting it into 2d array using reshape

arr1 = np.arange(1,10).reshape(3,3)  
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print()
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 1. Additon

 Elementwise Addition

In [58]:
# By one way

arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [59]:
# using Numpy

np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## 2. Subtraction

In [62]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 3. Division

In [63]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 4. Multiplication


In [66]:
# Element wise Product

arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [67]:
# Matrix Multiplication

arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [68]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## Finding Max value in matrix

In [69]:
arr1.max()

9

## Finding Index of max value elem

In [70]:
arr1.argmax()

8

## To find maximum value columnwise or Row wise

In [72]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# axis=0 represnt COLUMN
# axis=1 represnt ROW

arr1.max(axis = 0)

array([7, 8, 9])

In this output 7 is max from first column,
8 from second and 9 from third column

In [73]:
arr1.max(axis=1)

array([3, 6, 9])

## Finding Minimum value

In [76]:
arr1.min()

1

In [78]:
# GIves Index Value

arr1.argmin()


0

In [79]:
arr1.min(axis=0)

array([1, 2, 3])

In [80]:
arr1.min(axis=1)

array([1, 4, 7])

## How to add all the elements from same array and get output

In [81]:
np.sum(arr1)

45

### Sum all elements from each row or colun from array

In [82]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [83]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])



## Mean of array

In [84]:
np.mean(arr1)

5.0

## Finding square root of each element from array

In [87]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

## Standard Division

In [88]:
np.std(arr1)

2.581988897471611

##Exponent

In [89]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

## LOG

In [90]:
# log gives natural log

np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [91]:
# to find log base 10

np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])