<a href="https://colab.research.google.com/github/AkashSalmuthe/Python-Noteboks/blob/main/Predict_the_Price_of_Banglore_House.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model import LinearRegression

### Load Dataset

In [2]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB" 
df = pd.read_csv(path)

In [3]:
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

## Split the Data

* Remember this data is alredy cleaned

In [4]:
X = df.drop('price',axis=1)
y = df['price']

print('Shape of X : ',X.shape)
print('Shape of y : ',y.shape)

Shape of X :  (7120, 107)
Shape of y :  (7120,)


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


## Feature Scaling

In [6]:
sc = StandardScaler()
sc.fit(X_train)

X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

### Train model

In [7]:
lr = LinearRegression()
 
lr.fit(X_train, y_train)


LinearRegression()

In [8]:
lr.coef_


array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468905e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029424e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968545e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886278e-01,  8.03443207e-01,  2.99182164e+00,  3.86430413e-03,
        1.05037261e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -

In [9]:
 
lr.intercept_

95.0802729985955

## Predict the value of Home and Test

In [10]:
X_test[0, :]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [11]:
lr.predict([X_test[0, :]])

array([76.90661876])

In [12]:
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [13]:
# Orignal values
y_test


2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [14]:
# Compaire the result

lr.score(X_test, y_test)

0.7903837092682249

### Ridge and Lasso Regression

In [15]:
from sklearn.linear_model import Lasso, Ridge

In [16]:
rd = Ridge()

In [17]:
rd.fit(X_train,y_train)
rd.score(X_test,y_test)


0.7905686374336628

In [18]:
ls = Lasso()

ls.fit(X_train,y_train)
ls.score(X_test,y_test)

0.8036373003525774

Changing value of alpha ("In Formula it's LAMBDA")

In [19]:
rd2 = Ridge(alpha = 2 )
rd2.fit(X_train,y_train)
rd2.score(X_test,y_test)

0.7907530260397942

In [20]:
ls2 = Lasso(alpha = 5)

ls2.fit(X_train,y_train)
ls2.score(X_test,y_test)

0.8357349048024318

## Model Evaluation

### 1. Root Mean Square Error

In [21]:
# Predicted Vlaues by model = y_hat
y_pred = lr.predict(X_test)
y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [22]:
# Actual Values =  y
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [23]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [24]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print("MSE is : ",mse)
print("RMSE is : ",rmse)

MSE is :  4211.806905823335
RMSE is :  64.89843531105612


## R-Sqaured

In [25]:
from sklearn.metrics import r2_score

In [26]:
r2_score(y_test,y_pred)

0.7903837092682249

# ***Ploynomial Regression***

In [27]:
from sklearn.preprocessing import PolynomialFeatures

In [28]:
poly_reg = PolynomialFeatures(degree=2)

In [29]:
poly_reg.fit(X_train)

PolynomialFeatures()

In [30]:
X_train_poly = poly_reg.transform(X_train)
X_test_poly = poly_reg.transform(X_test)

In [31]:
X_train_poly.shape

(5696, 5886)

In [32]:
X_test_poly.shape

(1424, 5886)

In [33]:
lr = LinearRegression()

lr.fit(X_train_poly,y_train)

LinearRegression()

In [34]:
lr.score(X_test_poly,y_test)

0.9986669653198645

In [35]:
lr.predict([X_test_poly[0,:]])

array([80.])

In [36]:
y_pred = lr.predict(X_test_poly)
y_pred

array([ 80.,  40., 120., ...,  32.,  63., 180.])

In [37]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [38]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print("MSE is : ",mse)
print("RMSE is : ",rmse)

MSE is :  26.784581732155026
RMSE is :  5.17538227884231


## Support Vector Machine 

In [39]:
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

## Split DataSet

In [40]:
X = df.drop('price',axis=1)
y = df['price']

print('Shape X :',X.shape)
print('Shape y :',y.shape)

Shape X : (7120, 107)
Shape y : (7120,)


In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


### Feature Scaling

In [42]:
sc = StandardScaler()

sc.fit(X_train)

X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

### Train the Model

In [43]:
from sklearn.svm import SVR

In [44]:
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train,y_train)

SVR()

In [45]:
svr_rbf.score(X_test,y_test)

0.20638035840828173

In [46]:
svr_lin = SVR(kernel='linear')
svr_lin.fit(X_train,y_train)
svr_lin.score(X_test,y_test)

0.7962656700653191

In [47]:
svr_poly = SVR(kernel='poly')
svr_poly.fit(X_train,y_train)
svr_poly.score(X_test,y_test)

0.3039932069927379

## Predict the value of home and test




In [48]:
y_pred = svr_lin.predict(X_test)

In [49]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [50]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print("MSE = ",mse)
print("RMSE = ",rmse)

MSE =  4093.6210385966133
RMSE =  63.98141166461251


# ***SVC***

In [51]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [52]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [53]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [54]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [55]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [56]:
# Create dataFrame

df = pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])
df.head()

mean radius mean texture  ... worst fractal dimension target
0       17.99        10.38  ...                 0.11890    0.0
1       20.57        17.77  ...                 0.08902    0.0
2       19.69        21.25  ...                 0.08758    0.0
3       11.42        20.38  ...                 0.17300    0.0
4       20.29        14.34  ...                 0.07678    0.0

[5 rows x 31 columns]

In [57]:
df.shape

(569, 31)

### Split the data

In [58]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

print('Shape X :',X.shape)
print('Shape y :',y.shape)


Shape X : (569, 30)
Shape y : (569,)


In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (455, 30)
Shape of y_train =  (455,)
Shape of X_test =  (114, 30)
Shape of y_test =  (114,)


In [60]:
# Implementing SVC

from sklearn.svm import SVC

In [61]:
cls_rbf = SVC(kernel='rbf')
cls_rbf.fit(X_train,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


SVC()

In [62]:
cls_rbf.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9035087719298246

### Feature scaling

In [63]:
sc = StandardScaler()
sc.fit(X_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


StandardScaler()

In [64]:
X_train_sc = sc.transform(X_train)
y_train_sc = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


In [65]:
cls_rbf = SVC(kernel='rbf')
cls_rbf.fit(X_train,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


SVC()

In [66]:
cls_rbf.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9035087719298246

In [67]:
cls_poly = SVC(kernel='poly',degree=2)
cls_poly.fit(X_train,y_train)
cls_poly.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9035087719298246

In [68]:
cls_lin = SVC(kernel='linear')
cls_lin.fit(X_train,y_train)
cls_lin.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9385964912280702

# Decision Tree Reggression

In [69]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB" 
df = pd.read_csv(path)
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

In [70]:
X = df.drop('price',axis=1)
y = df['price']

print('Shape of X : ',X.shape)
print('Shape of y : ',y.shape)

Shape of X :  (7120, 107)
Shape of y :  (7120,)


In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


# Model training

In [72]:
from sklearn.tree import DecisionTreeRegressor

In [73]:
dt_reg = DecisionTreeRegressor(criterion='mse')
dt_reg.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


DecisionTreeRegressor(criterion='mse')

In [74]:
dt_reg.score(X_test,y_test)

0.8896706206089597

## Prediction

In [75]:
X_test.iloc[-1,:]

bath                               2.000000
balcony                            0.000000
total_sqft_int                  1566.000000
bhk                                2.000000
price_per_sqft                 11494.252874
                                   ...     
location_Hosur Road                0.000000
location_Horamavu Banaswadi        0.000000
location_Domlur                    0.000000
location_Mahadevpura               0.000000
location_Tumkur Road               0.000000
Name: 43, Length: 107, dtype: float64

In [76]:
pred = dt_reg.predict(X_test)
pred

array([ 83.  ,  39.95, 120.  , ...,  33.  ,  62.5 , 170.  ])

In [77]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

# **Random Forest Regression**

In [78]:
df.shape

(7120, 108)

In [79]:
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

### Spit the data

In [80]:
X = df.drop('price',axis=1)
y = df['price']

print('Shape of X : ',X.shape)
print('Shape of y : ',y.shape)

Shape of X :  (7120, 107)
Shape of y :  (7120,)


In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


### Model Training

In [82]:
from sklearn.ensemble import RandomForestRegressor

In [83]:
rf_reg = RandomForestRegressor(n_estimators=100,criterion='mse')
rf_reg.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


RandomForestRegressor(criterion='mse')

In [84]:
rf_reg.score(X_test,y_test)

0.8873423834334342

In [85]:
rf_reg = RandomForestRegressor(n_estimators=500,criterion='mse')
rf_reg.fit(X_train,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,


0.8912970067751751

In [86]:
rf_reg.score(X_test,y_test)

0.8912970067751751

In [87]:
y_pred = rf_reg.predict(X_test)
y_pred

array([ 79.58105,  39.92114, 119.782  , ...,  33.42323,  63.35392,
       176.074  ])

In [88]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

# SAve the **model**

### Using pickle

In [90]:
import pickle

In [91]:
pickle.dump(rf_reg,open('Random_Forest_Regression_Model','wb'))

In [92]:
rf_reg_model = pickle.load(open('Random_Forest_Regression_Model','rb'))

In [94]:
# rf_reg_model()

# ready to use model

### using joblib

In [95]:
import joblib 

In [96]:
joblib.dump(rf_reg,'Random_Forest_Regression_Model_2')

['Random_Forest_Regression_Model_2']

In [97]:
model_2 = joblib.load('Random_Forest_Regression_Model_2')

# **KNN Regression**

In [98]:
from sklearn.neighbors import KNeighborsRegressor

In [99]:
X = df.drop('price',axis=1)
y = df['price']

print('Shape of X : ',X.shape)
print('Shape of y : ',y.shape)

Shape of X :  (7120, 107)
Shape of y :  (7120,)


In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


### Model train

In [101]:
knn_reg = KNeighborsRegressor(n_neighbors=5)
knn_reg.fit(X_train,y_train)

KNeighborsRegressor()

In [102]:
knn_reg.score(X_test,y_test)

0.8858214084886539

In [103]:
y_pred = knn_reg.predict(X_test)
y_pred

array([ 77.378,  39.808, 120.2  , ...,  33.405,  63.   , 184.4  ])